version: '2'

services:
    mirage:
        build: 
            context: ./
            dockerfile: ./.docker/Dockerfile
        volumes:
            - ./app:/project/app
            - ./assets:/project/assets
            - /project/node_modules
        ports:
            - "3030:3030"
            - "3031:3031"